__version__ = '0.0.2'
__author__ = 'David Stainton'
__contact__ = 'dawuud@riseup.net'
__url__ = 'https://github.com/applied-mixnetworks/sphinxmixcrypto'
__license__ = 'GPL3'
__copyright__ = 'Copyright 2016-2017'
